package:
  name: nb_config_manager
  version: "0.1.2"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
  run:
    - python
    - notebook ==4.1.0

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-nb_config_manager
  license: BSD
